- apt:
    - build-essential
    - cmake
    - gitk
    - clang

- shell:
    - wget https://go.dev/dl/go1.23.1.linux-amd64.tar.gz
    - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz
    - rm -f go1.23.1.linux-amd64.tar.gz
