- apt:
    - build-essential
    - cmake
    - gitk
    - clang

- shell:
    - wget https://go.dev/dl/go1.23.1.linux-amd64.tar.gz
    - rm -rf /usr/local/go && tar -C /usr/local -xzf go1.23.1.linux-amd64.tar.gz
    - rm -f go1.23.1.linux-amd64.tar.gz

- shell:
    - wget https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    - chmod ugo+x nvim-linux-x86_64.appimage
    - mv nvim-linux-x86_64.appimage /usr/bin/nvim

- shell:
    - wget https://github.com/tree-sitter/tree-sitter/releases/latest/download/tree-sitter-linux-x64.gz
    - gunzip tree-sitter-linux-x64.gz
    - chmod ugo+x tree-sitter-linux-x64
    - mv tree-sitter-linux-x64 /usr/local/bin/tree-sitter

- snap:
    - code:
        classic: true
